version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# python:
#   install:
#     - requirements: docs/requirements.txt  # or just requirements.txt if it's in root

sphinx:
  configuration: docs/source/conf.py  # or conf.py if it's in root
