site_name: XLB Documentation

theme:
  name: material  # Optional but looks great

nav:
  - Home: index.md
  - API Reference: api_reference.md
  - Examples: examples.md
  - Velocity Sets: velocity_sets.md
  - Backend and Precision: backends_precision.md
  - Utilities: utilities.md